apiVersion: v1
kind: Service
metadata:
  labels:
    app: quarkus-resteasy
  name: quarkus-resteasy
  namespace: quarkus-resteasy
spec:
  clusterIP: 172.30.25.126
  clusterIPs:
  - 172.30.25.126
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: quarkus-resteasy
    deploymentconfig: quarkus-resteasy
  sessionAffinity: None
  type: ClusterIP
