apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  labels:
    app: quarkus-resteasy
  name: quarkus-resteasy
  namespace: quarkus-resteasy
spec:
  params:
  - default: quarkus-resteasy
    name: APP_NAME
    type: string
  - default: https://github.com/fcorodriguezrocha/quarkus-resteasy
    name: GIT_REPO
    type: string
  - default: master
    name: GIT_REVISION
    type: string
  - default: image-registry.openshift-image-registry.svc:5000/quarkus-resteasy/quarkus-resteasy
    name: IMAGE_NAME
    type: string
  - default: .
    name: PATH_CONTEXT
    type: string
  - default: openjdk-17-ubi8
    name: VERSION
    type: string
  tasks:
  - name: fetch-repository
    params:
    - name: url
      value: $(params.GIT_REPO)
    - name: revision
      value: $(params.GIT_REVISION)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: workspace
  - name: build
    params:
    - name: IMAGE
      value: $(params.IMAGE_NAME)
    - name: TLSVERIFY
      value: "false"
    - name: PATH_CONTEXT
      value: $(params.PATH_CONTEXT)
    - name: VERSION
      value: $(params.VERSION)
    runAfter:
    - fetch-repository
    taskRef:
      kind: ClusterTask
      name: s2i-java
    workspaces:
    - name: source
      workspace: workspace
  - name: deploy
    params:
    - name: SCRIPT
      value: oc rollout status deploy/$(params.APP_NAME)
    runAfter:
    - build
    taskRef:
      kind: ClusterTask
      name: openshift-client
  workspaces:
  - name: workspace
